name: Deploy Impressum with Private Address

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      - name: Create build folder
        run: mkdir -p site

      - name: Replace placeholder and convert to HTML
        env:
          ADDRESS: ${{ secrets.ADDRESS_PLAIN }}
      #  run: |
       #   sed "s/{{PRIVATE_ADDRESS}}/$ADDRESS/" impressum.md > site/impressum.md

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
