name: Build Impressum with Address as Image

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y imagemagick pandoc gettext

      - name: Create build directory
        run: mkdir -p site

      - name: Create image from address
        env:
          ADDRESS: ${{ secrets.ADDRESS_PLAIN }}
        run: |
          echo "$ADDRESS" | convert -background white -fill black -font Helvetica -pointsize 16 text:- address.png
          base64 address.png > address.b64

      - name: Replace placeholder with Base64 image
        run: |
          IMAGE_DATA=$(cat address.b64 | tr -d '\n')
          sed "s#\${ADDRESS_IMAGE}#<img src='data:image/png;base64,${IMAGE_DATA}' alt='Adresse'>#" impressum.md > site/impressum.md
          pandoc site/impressum.md -f markdown -t html -o site/impressum.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
